# name: Server CI

# on:
#   push:
#     branches: [main]
#     paths:
#       - "apps/server/**"
#   pull_request:
#     branches: [main]
#     paths:
#       - "apps/server/**"

#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Install Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 20

#       - name: Install PNPM
#         uses: pnpm/action-setup@v3
#         with:
#           version: 8
#           run_install: false

#       - name: Get pnpm store directory
#         shell: bash
#         run: |
#           echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

#       - uses: actions/cache@v3
#         name: Setup pnpm cache
#         with:
#           path: ${{ env.STORE_PATH }}
#           key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
#           restore-keys: |
#             ${{ runner.os }}-pnpm-store-

#       - name: Install dependencies
#         run: pnpm install

#       - name: Run test
#         run: pnpm run test

#       - name: Run E2E tests
#         run: pnpm run test:e2e